title: 立个flag先
author:
  name: 刘瑞琪
  email: 405782134@qq.com
description: > # this means to ignore newlines until "show_excerpts:"
  每天进步一..

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    github:  liuruiqi1993

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

collections_dir: collections
collections:
  html:
    output: true
    title: HTML
  js:
    output: true
    title: Javasript
  record:
    output: true
    title: 记录
  css:
    output: true
    title: Css
  react:
    output: true
    title: React
  vue:
    output: true
    title: Vue
  webpack:
    output: true
    title: Webpack
    
plugins:
 - jekyll-feed
 - jekyll-seo-tag
